name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        # version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: latest
        args: "> linter.json"
        skip-go-installation: true
        
    - name: Test
      run: go test -json -coverprofile=coverage.out ./...  > report.json

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      with:
        args: >
          -Dsonar.organization=knightpp
          -Dsonar.projectKey=knightpp_ita-tasks
          -Dsonar.go.coverage.reportPaths=coverage.out
          -Dsonar.go.tests.reportPaths=report.json
          -Dsonar.go.golangci-lint.reportPaths=linter.json
          -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
 
