name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -coverprofile=coverage.out -v ./...
      
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        # version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: latest
        # if set to true then action uses pre-installed Go
        skip-go-installation: true
